### PR TITLE
feat: adds 1.19.3 support

### PR DESCRIPTION
**Pull request by OGRages**
Added v1_19_R2 module and updated NMS code to work with latest 1.19.3

### CODE REVIEW

**Comment by Bobcat00** [comment]
This should be linked to issue #365

**Comment by timbru31** [comment]
Thanks a lot! I can see that the main change is around `setEntityId()`.
Will verify and test the change and then merge in.

**Comment by Navoei** [comment]
I cant seem to compile @OGRages 's plugin as I do not have authentication.

**Comment by ItzSave** [comment]
Anymore luck on this? It's not possible to build due to private repos.

**Comment by Bobcat00** [comment]
See https://github.com/Bobcat00/SilkSpawners/releases/tag/v1-19-3 for an unofficial release.

**Review by timbru31 — APPROVED** [review]
Thanks again and sorry for the delay :)

**Pull request merged**
